const productos = {
    productos3d: [
    {
      id: "p1",
      categoria: "pieza3d",
      nombre: "Escuadra de refuerzo",
      imagen: "../images/p13w_jc3d.jpg",
      precio: "Consultar precio vía contacto",
      descripcion: "Pieza de refuerzo estructural para uniones en ángulo recto. Ideal para proyectos de carpintería y construcción.",
      dimensiones: "50 x 50 x 3 mm",
      material: "PETG",
      peso: "",
      uso: "Carpintería y construcción",
      otras_caracteristicas: "Alta resistencia mecánica",
      observaciones: "Se puede personalizar según necesidades",
      garantia: "6 meses (garantía legal)"
    },
    {
        id: "p2",
        categoria: "pieza3d",
        nombre: "Soporte de barra intermedia",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "Soporte diseñado para sostener barras intermedias en estructuras. Perfecto para proyectos de organización y almacenamiento.",
        dimensiones: "A medida según aplicación",
        material: "PETG",
        peso: "",
        uso: "Organización y almacenamiento",
        otras_caracteristicas: "Diseño modular",
        observaciones: "Se adapta a diferentes diámetros de barra",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p3",
        categoria: "pieza3d",
        nombre: "Soporte barra lateral",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "",
        material: "PETG",
        peso: "",
        uso: "",
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p4",
        categoria: "pieza3d",
        nombre: "Soporte escuadra de unión",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "40 x 20 x 3,0 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p5",
        categoria: "pieza3d",
        nombre: "Soporte escuadra pequeño",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "20 x 20 x 3,0 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p6",
        categoria: "pieza3d",
        nombre: "Soporte escuadra mediano",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "25 x 25 x 3,2 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p7",
        categoria: "pieza3d",
        nombre: "Soporte triangular",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "<br> 20 x 20 mm <br> 25 x 25 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p8",
        categoria: "pieza3d",
        nombre: "Soporte triangular de unión",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "40 x 20 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p9",
        categoria: "pieza3d",
        nombre: "Placa de unión",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "80 x 40 x 3 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p10",
        categoria: "pieza3d",
        nombre: "Soporte universal",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "Soporte versátil para múltiples aplicaciones.",
        dimensiones: "30 x 30 x 3 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p11",
        categoria: "pieza3d",
        nombre: "Soporte Elegance",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p12",
        categoria: "pieza3d",
        nombre: "Pasacables con rosca mediano",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "Ø50 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    },
    {
        id: "p13",
        categoria: "pieza3d",
        nombre: "Pasacables con rosca grande",
        imagen: "../images/p13w_jc3d.jpg",
        precio: "Consultar precio vía contacto",
        descripcion: "",
        dimensiones: "Ø60 mm",
        material: "PETG",
        peso: "",
        uso: "",        
        otras_caracteristicas: "",
        observaciones: "",
        garantia: "6 meses (garantía legal)"
    }
  ],
  muebles: [
    {
      id: "m1",
      categoria: "mueble",
      nombre: "Mueble de Cocina Personalizado",
      imagen: "../images/mueble_1.jpg",
      precio: "Consultar precio vía contacto",
      descripcion: "Muebles de cocina diseñados específicamente para tu espacio y necesidades.",
      dimensiones: "A medida",
      material: "Madera de pino y melamina",
      peso: "",
      uso: "Cocina",
      otras_caracteristicas: "Incluye cajones con correderas suaves",
      observaciones: "Diseño personalizado según medidas del cliente",
      garantia: "1 año de garantía"
    },
    {
      id: "m2",
      categoria: "mueble",
      nombre: "Estantería Modular",
      imagen: "../images/mueble_1.jpg",
      precio: "Consultar precio vía contacto",
      descripcion: "Sistema de estanterías modulares que se adaptan a cualquier espacio.",
      dimensiones: "A medida",
      material: "Madera de pino tratada",
      peso: "",
      uso: "Hogar y oficina",
      otras_caracteristicas: "Módulos intercambiables",
      observaciones: "Se puede expandir según necesidades",
      garantia: "1 año de garantía"
    },
    {
      id: "m3",
      categoria: "mueble",
      nombre: "Mesa de Trabajo",
      imagen: "../images/mueble_1.jpg",
      precio: "Consultar precio vía contacto",
      descripcion: "Mesa de trabajo ergonómica con almacenamiento integrado.",
      dimensiones: "A medida",
      material: "Madera de pino y metal",
      peso: "",
      uso: "Oficina y taller",
      otras_caracteristicas: "Incluye cajones y repisas",
      observaciones: "Diseño ergonómico para largas jornadas",
      garantia: "1 año de garantía"
    },
    {
      id: "m4",
      categoria: "mueble",
      nombre: "Rack para TV",
      imagen: "../images/mueble_1.jpg",
      precio: "Consultar precio vía contacto",
      descripcion: "Rack personalizado para TV con cableado organizado.",
      dimensiones: "A medida",
      material: "Madera de pino y MDF",
      peso: "",
      uso: "Sala de estar",
      otras_caracteristicas: "Cableado oculto y ventilación",
      observaciones: "Incluye espacios para equipos de audio",
      garantia: "1 año de garantía"
    },
    {
      id: "m5",
      categoria: "mueble",
      nombre: "Mueble de Baño",
      imagen: "../images/mueble_1.jpg",
      precio: "Consultar precio vía contacto",
      descripcion: "Muebles de baño resistentes a la humedad y personalizados.",
      dimensiones: "A medida",
      material: "Madera tratada y melamina",
      peso: "",
      uso: "Baño",
      otras_caracteristicas: "Resistente a la humedad",
      observaciones: "Diseño que aprovecha el espacio disponible",
      garantia: "1 año de garantía"
    }
  ]
}
  